
services:

  app: &app
    tty: true
    stdin_open: true
    build:
      context: .
      target: contracts
    environment:
      dapk: "8dc139be3c85d64e2420f93eaf7a90d547f2b6fd3ebd0a72d4dce30a1bf4f145"
      ETHERSCAN_API_KEY: "EDBKYENP4HQJ3B5QAKJXUMDK245521HN7J"
    volumes:
      - ./contract/artifacts:/usr/app/contract/artifacts

  hello:
    <<: *app
    command: "npx hardhat --verbose"

  compile: 
    <<: *app
    command: "npx hardhat compile --force --verbose"

  test:
    <<: *app
    command: "npx hardhat test --verbose"

  console:
    <<: *app
    command: "npx hardhat console --verbose"

  node:
    <<: *app
    ports:
      - "8545:8545"
    command: "npx hardhat node"

  clean:
    <<: *app
    ports:
      - "8545:8545"
    command: "npx hardhat clean"



  #llama a los scritps que están en package.json
  script:
    <<: *app
    command:
      - npm
      - run
      - test
